### ISSUE TITLE
Upgrade to be used with Laravel 6.*

### ISSUE THREAD

**Issue by keriat** [gerardojbaez/vehicle#3]
Hey, @gerardojbaez!

Thanks for an awesome package and big work done.

But as far as I see — you don't maintain this package anymore.

Our team successfully adapted this package for Laravel >=6 and we're willing to continue maintaining it.

So please, give me some access to this repo and package on [Packagist](https://packagist.org/packages/gerardojbaez/vehicle) — I would love to continue your work.

**Comment by matbrgz** [comment]
@gerardojbaez Please give a second at this.

**Comment by keriat** [comment]
@MatheusRV @gerardojbaez guys, what's up? Any chance to contribute to the Vehicle?

**Comment by keriat** [comment]
@MatheusRV @gerardojbaez I'm really sorry to disturb you but we're using this package in two projects already so we'll definitely maintain it at Fruitware

Please let me know either it's possible to continue contribution into this package or we'll continue development and maintenance in very new project (_which is actually not cool if you ask me, because nobody among current package audience will be awarded about new package and we can actually help this people to continue usage_)

**Comment by keriat** [comment]
Hey, @MatheusRV  @gerardojbaez ✊

How are you, mates?

Hope you’ve gone through the lock-down and self-isolation without struggle and you staying safe right now!

Please let me know if we can transfer the ownership. The “no” answer is accepted as well without a single offense taken 😉

Looking forward with hope to consider next moves
Thanks in advance, again, stay safe ✊

**Comment by gerardojbaez** [comment]
Hey @keriat ✌

Thanks! I hope you are staying safe and doing well!

Sure, I can transfer the ownership. Please make sure to keep the "Copyright (c) 2016 Gerardo J. Báez" part in the License, you can add your name and the year you started maintaining your fork to the present; other than that, you are free to rename and improve it as needed!

What would be the next step? 🤔

**Comment by keriat** [comment]
Sure, will remain the initial copyrights.
Next steps will be:
1) support for the laravel 7.*

**Comment by gerardojbaez** [comment]
Alright! I've initiated the transfer.

**Comment by keriat** [comment]
@gerardojbaez hey, mate! 
Maybe I’m missing something, no access yet.
As well as no request to join, owe o else.

Pls, lmk when we can set it up to update

**Comment by gerardojbaez** [comment]
@keriat Hey! 

That's weird, I've used the Transfer Repository feature:
![image](https://user-images.githubusercontent.com/11788389/83940819-e23fb800-a7b4-11ea-92cd-ce5becba4612.png)

I will abort and try it again. 

UPDATE:

Tried it and got "keriat/vehicle already exists". I've sent you an invite as a collaborator. Please let me know your username on Packagist so I can invite you there as well.

**Comment by keriat** [comment]
got the push access to the repo, thanks!

I'll let you know any new action 🤘
